import { Providers } from "@/components/Providers";
import MainLayout from "@/layout";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
import "windi-devtools";
import "windi.css";
import "./globals.css";

export const metadata: Metadata = {
	title: "MNEMONIC SCANNER",
	description: "Generated by MNEMONIC SCANNER",
};

// If loading a variable font, you don't need to specify the font weight
const inter = Roboto({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-plus",
	weight: ["100", "300", "400", "500", "700"],
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html
			lang="en"
			className={`${inter.variable}`}
		>
			<head></head>
			<body>
				<Providers>
					<MainLayout>{children}</MainLayout>
				</Providers>
			</body>
		</html>
	);
}
